import { Router, type IRouter } from "express";
import healthRouter from "./health";
import applicationsRouter from "./applications";
import adminRouter from "./admin";
import adminDashboardRouter from "./admin-dashboard";
import adminUsersRouter from "./admin-users";
import adminAssignmentsRouter from "./admin-assignments";
import adminInterviewRouter from "./admin-interview";
import adminDecisionRouter from "./admin-decision";
import evaluatorRouter from "./evaluator";
import adminStudentsRouter from "./admin-students";
import adminCohortsRouter from "./admin-cohorts";
import adminProgramsRouter from "./admin-programs";
import adminSessionsRouter from "./admin-sessions";
import adminTasksRouter from "./admin-tasks";
import adminAnnouncementsRouter from "./admin-announcements";
import studentRouter from "./student";
import adminActivityRecordsRouter from "./admin-activity-records";
import adminProjectsRouter from "./admin-projects";
import adminMvp4ArtifactsRouter from "./admin-mvp4-artifacts";
import adminFeedbackRouter from "./admin-feedback";
import adminTagsRouter from "./admin-tags";
import adminReportsRouter from "./admin-reports";
import studentMvp4Router from "./student-mvp4";
import siteContentRouter from "./site-content";
import activationRouter from "./activation";
import peopleRouter from "./people";
import adminPeopleAvatarsRouter from "./admin-people-avatars";
import storageServeRouter from "./storage-serve";
import adminMeetingsRouter from "./admin-meetings";
import adminOpsTasksRouter from "./admin-ops-tasks";
import adminDocumentsRouter from "./admin-documents";

const router: IRouter = Router();

router.use(healthRouter);
router.use(applicationsRouter);
router.use(adminRouter);
router.use(adminDashboardRouter);
router.use(adminUsersRouter);
router.use(adminAssignmentsRouter);
router.use(adminInterviewRouter);
router.use(adminDecisionRouter);
router.use(evaluatorRouter);
router.use(adminStudentsRouter);
router.use(adminCohortsRouter);
router.use(adminProgramsRouter);
router.use(adminSessionsRouter);
router.use(adminTasksRouter);
router.use(adminAnnouncementsRouter);
router.use(studentRouter);
router.use(adminActivityRecordsRouter);
router.use(adminProjectsRouter);
router.use(adminMvp4ArtifactsRouter);
router.use(adminFeedbackRouter);
router.use(adminTagsRouter);
router.use(adminReportsRouter);
router.use(studentMvp4Router);
router.use(siteContentRouter);
router.use(activationRouter);
router.use(peopleRouter);
router.use(adminPeopleAvatarsRouter);
router.use(storageServeRouter);
router.use(adminMeetingsRouter);
router.use(adminOpsTasksRouter);
router.use(adminDocumentsRouter);

export default router;
